/* Optional neighborhood conversations. No rewards or campaign mutations. */
(function(root){
const entries=[
 ['lou','Lou Rizzo','DELIVERY DRIVER','satriales','exterior',[4,10.5],'Man with a delivery cap','If this truck gets one more parking ticket, I’m putting the tickets on the menu.',[['Busy day?','Six stops before lunch. Every customer says their order should have been first. Apparently I work for six presidents.'],['Know the neighborhood?','Most of us are here for lunch. The regulars settle in after the rush. Ask around inside if you missed somebody.']]],
 ['mara','Mara Russo','NEIGHBOR','satriales','exterior',[16.5,11],'Woman with a shopping bag','I came for a quarter pound of provolone. I’ve heard three arguments and still haven’t got my cheese.',[['What were they arguing about?','Parking. Baseball. Whether a sandwich can have too much vinegar. The big questions.'],['You live nearby?','Two blocks over. Close enough to smell the bread, far enough that nobody asks me to help unload it.']]],
 ['nicky','Nicky Ferraro','COUNTER CLERK','satriales','interior',[10,8],'Clerk in an apron','Take a number. Unless you’re just looking, in which case you can take your time.',[['What’s good today?','The roast peppers. Everybody orders meat and forgets the peppers. That’s a mistake.'],['Anyone else working today?','There are customers, there are regulars, and there are people who don’t bother with the counter. The last group uses the back room.']]],
 ['sal','Sal Marino','RETIRED PLUMBER','satriales','interior',[5,12],'Older man with coffee','Thirty years fixing pipes. Now my wife says I spend too much time sitting down. I thought that was the point.',[['Still taking jobs?','Only the ones that end with a sandwich. You’d be surprised how many people can’t meet that price.'],['Any advice?','Listen before you start turning things. Works on pipes. Works on people, too.']]],
 ['gina','Gina DeLuca','HOST','vesuvio','interior',[14,7],'Host with a reservation book','Table for one? Nothing wrong with that. Less arguing about the appetizer.',[['How’s the evening looking?','Two birthdays and an anniversary. One of them forgot which anniversary. I put them near the bar.'],['Can I speak to the chef?','Try the kitchen. Just stay out of the path between the stove and the pass.']]],
 ['aldo','Aldo Ricci','REGULAR DINER','vesuvio','interior',[5,11.5],'Diner in a gray jacket','My wife says I order the same thing every week. I say consistency is a virtue.',[['What’s your usual?','Veal, salad, espresso. If I wanted surprises, I’d open my mail.'],['Do you eat here often?','Enough that they know my name. Not enough that they let me choose the music.']]],
 ['bruno','Bruno Costa','PREP COOK','vesuvio','backroom',[6,10],'Cook with rolled sleeves','Watch the floor. Somebody dropped olive oil, and apparently that somebody is always me.',[['What are you making?','Enough chopped onions to make the entire dining room cry. The trick is not joining in.'],['Enjoy working here?','The food’s good. The tickets never stop. Ask me again after the last table leaves.']]],
 ['val','Val Mercer','VALET','vesuvio','exterior',[6,11],'Attendant by the curb','Keep your claim ticket. Remembering a face is easy. Remembering which silver sedan is yours is another thing.',[['Any interesting cars?','Everybody wants a Cadillac. Nobody wants to admit they can’t parallel park one.'],['Quiet shift?','It’s quiet until all the tables finish at once. Then it’s a parade with worse manners.']]],
 ['dana','Dana Moretti','BARTENDER','bing','interior',[12.5,7],'Bartender polishing a glass','We’re between crowds. Best time to hear yourself think, if that’s what you came for.',[['Long night ahead?','Depends on the jukebox. Three good songs can save a shift. One guy playing the same song can ruin it.'],['Where’s the office?','Past the club, through the rear door. People back there usually have less interest in the music.']]],
 ['mickey','Mickey Bell','REGULAR','bing','interior',[6.5,12],'Man nursing a soda','Just a soda. Everybody assumes you need a reason.',[['What brings you here?','My apartment has a broken radio. This place has a working one and somebody else washes the glasses.'],['Good music tonight?','Ask me after they find the volume knob. Right now the bass is doing all the talking.']]],
 ['ray','Ray Gallo','DOORMAN','bing','exterior',[6,10.5],'Man in a dark coat','If you’re waiting for somebody, don’t block the entrance. That’s the whole speech.',[['Always this quiet?','Before the crowd comes, yes. I try to appreciate it while it lasts.'],['Worked here long?','Long enough to know that “I know the owner” isn’t a useful description around here.']]],
 ['leon','Leon Price','SERVICE TECHNICIAN','bing','backroom',[5,11],'Man carrying a tool bag','The ice machine works. The complaint is that the ice is too cold. That’s a new one.',[['Can you fix everything?','I can fix machines. Expectations are somebody else’s department.'],['What’s in the bag?','Tools, spare parts, and a sandwich I keep forgetting about. In that order of importance.']]],
 ['irene','Irene Walsh','TRUCK DRIVER','docks','exterior',[5,11],'Driver with a thermos','I’ve been waiting an hour to unload. My coffee gave up before I did.',[['Where are you headed?','West, if they ever finish counting. Right now I’m considering retirement in this parking space.'],['Who handles deliveries?','The foreman’s usually inside the warehouse. Dispatch handles schedules, not arguments.']]],
 ['pete','Pete Novak','FORKLIFT OPERATOR','docks','interior',[12,11.5],'Worker in a safety vest','Stay out of the painted lanes. Even when the forklift’s parked. Habits keep you in one piece.',[['How’s the shift?','Crates come in, crates go out. The exciting part is when the labels match.'],['What’s in the crates?','A thousand things I don’t need. Somebody else’s problem, packed very carefully.']]],
 ['denise','Denise Hall','DISPATCH CLERK','docks','backroom',[12.5,8],'Clerk holding a clipboard','If you’re here about a late truck, get in line. If you’re here about an early one, I’d like a photograph.',[['Lots of paperwork?','Three copies of everything. One for the office, one for the driver, one to disappear mysteriously.'],['When does your shift end?','According to the clock, six. According to this stack of forms, sometime next spring.']]],
 ['oscar','Oscar Vega','DOCKHAND','docks','interior',[7,11.5],'Worker in a knit cap','I finally bought decent boots. Now I’m afraid to get them dirty. That’s no way to work a dock.',[['What’s the weather doing?','Wind off the water. If somebody tells you it’s pleasant, they’re selling a boat.'],['Any plans after work?','Dinner with my kids. They want pizza. I want a chair. We can probably compromise.']]],
 ['elsie','Elsie Romano','PARISH VOLUNTEER','church','exterior',[5,10.5],'Woman tending the flowers','These flowers need water every morning. People could learn something about asking for help before they wilt.',[['The garden looks good.','Thank you. The roses are stubborn, but I’m more stubborn. We have an understanding.'],['Is the parish open?','Father Matteo is inside. The little room beyond the sanctuary is where we sort donations.']]],
 ['tom','Tom Heller','CHOIR MEMBER','church','interior',[9,9],'Man holding sheet music','I practice all week, then the organ starts and I forget where the first note went.',[['What are you rehearsing?','Sunday’s hymns. The notes haven’t changed, but apparently my voice has.'],['Why keep singing?','For about three minutes, everybody in the room is trying to do the same good thing. I like that.']]],
 ['bea','Bea Lombardi','VOLUNTEER','church','backroom',[11.5,10.5],'Woman sorting groceries','Pasta on this side, tins on that side. Organization is what stands between charity and a pantry avalanche.',[['Need a hand?','Kind of you, but I’ve got a system. Sometimes the best help is leaving somebody room to finish.'],['Busy lately?','Always. We don’t ask people to explain why they need dinner. We just try to have it ready.']]],
 ['joey','Joey Serra','NEIGHBOR','church','exterior',[15.5,11],'Man sitting near the steps','It’s quieter here than at home. My upstairs neighbor discovered the trumpet.',[['Is he any good?','He’s enthusiastic. The walls are thin. Those are the two facts I can confirm.'],['You come here often?','Only when I need ten minutes without somebody trying to sell me something.']]],
 ['evan','Evan Brooks','RECEPTIONIST','hotel','interior',[14,6.5],'Clerk behind the desk','Good evening. If your reservation is under another name, it helps if you remember that name.',[['Busy hotel?','A convention downstairs. Everyone has the same briefcase and nobody has the right room key.'],['Where are the private rooms?','Past the lobby. The suite is up the stairs, through the door at the rear.']]],
 ['doris','Doris Shaw','GUEST','hotel','interior',[11,10.5],'Guest with a travel bag','I asked for a quiet room. They gave me one beside an ice machine. It’s very quiet between buckets.',[['Here on business?','Visiting my sister. She says the hotel is nicer than her spare room. I think she likes her spare room.'],['How was the trip?','Late train, cold sandwich, beautiful sunset. I’m trying to remember the last part.']]],
 ['felix','Felix Grant','PORTER','hotel','exterior',[6,10.5],'Porter by the entrance','People pack for a weekend like they’re emigrating. I have the shoulders to prove it.',[['What’s the strangest luggage?','A man once checked in with an empty birdcage. I decided not to ask.'],['Do you like the job?','I meet everybody and have to remember nobody. There are worse arrangements.']]],
 ['vera','Vera Santos','HOUSEKEEPER','hotel','backroom',[9,11.5],'Housekeeper by the window','I’m finishing up. Funny how people want a room spotless and then immediately put their shoes on the furniture.',[['Long shift?','Long enough. My bus does not accept “one more room” as an excuse.'],['Nice view from here.','It is. I try to look at it once before I close the curtains. Otherwise you forget it’s there.']]]
];
const npcs=Object.fromEntries(entries.map(([id,name,role,location,room,position,label,intro,topics])=>[id,{name,role,location,room,position,label,intro,topics}]));
if(typeof module!=='undefined')module.exports=npcs;root.AmbientNPCs=npcs;
})(typeof window!=='undefined'?window:globalThis);
