(function(){
'use strict';
const G=Game,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=G.fresh(),view='world',role='fixer',lastToast,manual=null,saved=null,soundOn=false,storageOK=true;
const music=JerseyMusic.create();
const SAVE='made-in-jersey-autosave-v1',MANUAL='made-in-jersey-manual-v1';
function readSave(key){try{const raw=localStorage.getItem(key);if(!raw)return null;const x=JSON.parse(raw);return G.migrateSave(x);}catch(e){return null;}}
saved=readSave(SAVE);manual=readSave(MANUAL);
function save(){if(!state.started)return;try{localStorage.setItem(SAVE,JSON.stringify(state));$('#save-status').textContent='PROGRESS SAVED';storageOK=true;}catch(e){storageOK=false;$('#save-status').textContent='SAVE UNAVAILABLE';}}
function toast(t){clearTimeout(lastToast);$('#toast').textContent=t;$('#toast').classList.add('show');lastToast=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function modal(content){Scene.cancelApproach();const d=$('#modal');d.innerHTML=content;if(!d.open)d.showModal();d.scrollTop=0;}
function closeModal(){if(!state.started)return;$('#modal').close();}
function modalTitle(title){return `<div class="modal-top"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close" aria-label="Close dialog">×</button></div>`;}
function morality(){return state.morality>=25?'A conscience, still':state.morality<=-25?'Made of harder things':'Walking the line';}
function commit(action){const hadInteraction=!!(state.dialog||state.combat),history=state.history[0],oldLevel=Math.floor(state.xp/100);if(action()===false)return;save();render();if(state.death||!hadInteraction&&(state.dialog||state.combat)){requestAnimationFrame(()=>$('.scene-frame').scrollIntoView({behavior:'smooth',block:'start'}));}if(state.history[0]&&state.history[0]!==history)toast(state.history[0]);if(Math.floor(state.xp/100)>oldLevel)toast('Reputation increased. All skills +1.');if(state.ending)ending();}
function setView(v){Scene.cancelApproach();view=v;render();window.scrollTo({top:0,behavior:'instant'});if(v==='world'&&(state.dialog||state.combat))requestAnimationFrame(()=>$('.scene-frame').scrollIntoView({block:'start'}));}
function render(){
 music.select(state.location,G.roomOf(state),state.combat?'combat':state.ending?'ending':'explore');
 if(soundOn)$('#sound').title=music.title();
 const loc=G.locations[state.location],roomInfo=G.roomInfo(state),sk=G.skills(state);$('.scene-column').classList.toggle('conversing',!!(state.dialog||state.combat));$('#world-view').hidden=view!=='world';$('#journal-view').hidden=view!=='journal';$('#character-view').hidden=view!=='character';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 $('#location-name').textContent=loc.name;$('#location-tag').textContent=roomInfo.tag;$('#district').textContent=loc.district+', NEW JERSEY · 1999';$('#scene-region').textContent=G.roomOf(state)==='exterior'?loc.district:roomInfo.name.toUpperCase();$('#scene').setAttribute('aria-label',loc.name+' — '+roomInfo.name+'. Click to walk; use the labeled doors to move between rooms.');
 $('#act-label').textContent=state.stage<3?'ACT I · THE ENVELOPE':state.stage<6?'ACT II · THE LEDGER':'ACT III · THE FAMILY';
 $('#chapter-title').textContent=state.stage<3?'An associate. For now.':state.stage<6?'Getting your hands dirty.':'A seat at the table.';
 $('#chapter-progress').style.width=(state.stage/8*100)+'%';$('#chapter-count').textContent=Math.min(state.stage,8)+' OF 8 CHAPTERS COMPLETE';$('#quest-count').textContent=state.ending?'✓':1+Object.values(state.side).filter(v=>v==='active').length;
 $('#objective-title').textContent=G.quests[state.stage][0];$('#objective-text').textContent=G.quests[state.stage][1];$('#morality-marker').style.left=(100-state.morality)/2+'%';$('#alignment-value').textContent=morality();$('#morality-marker').title='Morality: '+state.morality;
 $('#player-class').textContent='Level '+(1+Math.floor(state.xp/100))+' · '+G.classes[state.role].name;$('#player-health').style.width=state.hp+'%';$('#health-number').textContent=state.hp;$('#cash').textContent='$'+state.cash.toLocaleString();$('#respect').textContent=state.respect;$('#heat').textContent=state.heat+'%';
 $('#companion-name').textContent=G.people[state.companion][0];$('#companion-ability').textContent=state.companion==='silvio'?'Counsel · +2 focus':state.companion==='chris'?'Backup · −28 resolve':'Distraction · −22 resolve';
 Scene.portrait($('#player-portrait'),'player');Scene.portrait($('#companion-portrait'),state.companion);Scene.set(state.location,G.roomOf(state),G.nearbyPeople(state));renderCinematic();renderRooms();
 $('#hotspots').innerHTML=Scene.hotspotPositions().map(p=>`<button class="hotspot npc-hotspot" aria-label="Approach ${esc(G.personLabel(state,p.id))}" title="${esc(G.personLabel(state,p.id))}" data-talk="${p.id}" style="left:${p.x}%;top:${p.y}%" ${state.death||state.dialog||state.combat||state.ending?'disabled':''}><span class="qmark">◌</span>${(state.met||[]).includes(p.id)?esc(G.people[p.id][0].split(' ')[0]):'Talk'}</button>`).join('')+Scene.doorPositions().map(p=>`<button class="hotspot door-hotspot" data-room="${p.room}" style="left:${p.x}%;top:${p.y}%" ${state.death||state.dialog||state.combat||state.ending?'disabled':''}>↳ ${esc(doorLabel(p.room))}</button>`).join('')+Scene.inspections().map(p=>`<button class="hotspot inspect-hotspot" data-inspect="${p.id}" style="left:${p.x}%;top:${p.y}%" aria-label="Inspect ${esc(p.label)}" title="${esc(p.label)}" ${state.death||state.dialog||state.combat||state.ending?'disabled':''}>⌕</button>`).join('');$('#travel-open').disabled=!!(state.death||state.dialog||state.combat||state.ending);renderInteraction();interactionStatus();if(view==='journal')renderJournal();if(view==='character')renderCharacter();
}
function renderCinematic(){
 const el=$('#cinematic'),dialog=G.dialogue(state),combat=state.combat,active=!!(dialog||combat||state.death);el.hidden=!active;$('.scene-column').classList.toggle('cinematic-active',active);if(!active){el.innerHTML='';return;}
 const id=dialog?.who||(combat?.kind==='docks'?'vinnie':combat?.kind==='final'?'bodyguard':combat?.kind==='alley'?'enforcer':combat?.kind==='tail'?'hitman':'bodyguard');
 const name=state.death?state.death.enemy:dialog?G.people[id][0]:G.combatInfo(state).enemy;
 el.innerHTML=`<div class="camera-caption">${state.death?'YOU DIED':combat?'BATTLE · ROUND '+combat.round:'CONVERSATION'}<span>${esc(G.locations[state.location].name)}</span></div><div class="closeup-pair"><figure><canvas id="closeup-player" width="640" height="720" aria-label="Your character"></canvas><figcaption>You <small>${state.hp} HP</small></figcaption></figure><div class="camera-divider">${state.death?'×':combat?'VS':'◆'}</div><figure><canvas id="closeup-speaker" width="640" height="720" aria-label="${esc(name)}"></canvas><figcaption>${esc(name)}<small>${combat?combat.enemy+' / '+combat.max+' resolve':state.death?'Fatal encounter':esc(G.people[id][1])}</small></figcaption></figure></div>`;
 Scene.closeup($('#closeup-player'),'player',{battle:!!combat||!!state.death});Scene.closeup($('#closeup-speaker'),id,{battle:!!combat||!!state.death});
}
function roomName(id){return id==='exterior'?(state.location==='church'?'Courtyard':state.location==='docks'?'Loading yard':'Street'):G.rooms[state.location][id].name;}
function doorLabel(id){const name=roomName(id).replace(/^The /,'the ');return id==='exterior'?'Go outside':G.roomOf(state)==='exterior'?'Enter '+name:'To '+name;}
function renderRooms(){const current=G.roomOf(state),blocked=!!(state.death||state.dialog||state.combat||state.ending);$('#room-navigation').innerHTML=`<span class="room-prefix">⌂</span>${['exterior','interior','backroom'].map((id,i)=>`${i?'<span class="room-separator">/</span>':''}<button data-room="${id}" ${id===current?'aria-current="location"':''} ${blocked||id===current||!G.exits(state).includes(id)?'disabled':''}>${esc(roomName(id))}</button>`).join('')}<span class="room-status">${current==='exterior'?'OUTSIDE':'INSIDE'}</span>`;}
function changeRoom(id){Scene.cancelApproach();if(G.moveRoom(state,id)){save();render();$('.location-heading').scrollIntoView({block:'start',behavior:'smooth'});}}
function inspectObject(id){if(state.death||state.dialog||state.combat||state.ending)return;const object=Scene.inspections().find(o=>o.id===Number(id));if(!object)return;modal(`${modalTitle(esc(object.label))}<div class="eyebrow">${esc(G.locations[state.location].name)} · ${esc(G.roomInfo(state).name)}</div><p class="modal-intro" style="margin-top:20px">${esc(object.detail)}</p>${object.label==='The stage show'?'<div class="performer-portraits"><figure><canvas id="jade-portrait" width="320" height="360" aria-label="Jade, stage performer"></canvas><figcaption>Jade</figcaption></figure><figure><canvas id="ruby-portrait" width="320" height="360" aria-label="Ruby, stage performer"></canvas><figcaption>Ruby</figcaption></figure></div>':''}<button class="primary" data-action="close">Keep exploring</button>`);if(object.label==='The stage show'){Scene.closeup($('#jade-portrait'),'jade');Scene.closeup($('#ruby-portrait'),'ruby');}}
function sceneStatus(text,action,label){
 const panel=$('#scene-controls');panel.hidden=!text;$('#scene-status').textContent=text||'';
 const button=$('#scene-control-action');button.dataset.action=action||'';button.textContent=label||'';
}
function interactionStatus(){
 if(state.death)sceneStatus('You died — resources lost','show-conversation','Respawn options');
 else if(state.dialog)sceneStatus('Talking with '+G.people[G.dialogue(state).who][0],'show-conversation','View conversation');
 else if(state.combat)sceneStatus('Confrontation in progress','show-conversation','View actions');
 else if(G.dangers(state).length)sceneStatus('Armed threat nearby','show-conversation','View encounter');
 else sceneStatus();
}
function approachPerson(id){if(!window.canWalk())return;const label=G.personLabel(state,id);const ok=Scene.approach(id,()=>{if(window.canWalk()){commit(()=>G.talk(state,id));$('#footer-tip').textContent='Nothing personal. Just choices.';}});if(ok&&!state.dialog){$('#footer-tip').textContent='Walking to '+label+' · click the ground to cancel';sceneStatus('Walking to '+label,'cancel-walk','Cancel');document.querySelectorAll('[data-talk]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.talk===id)));}else if(!ok)toast('There is no clear path. Try approaching from another side.');}
function renderInteraction(){const el=$('#interaction');
 if(state.death){const d=state.death;el.innerHTML=`<section class="death-panel"><div class="eyebrow">DEATH ${state.deaths} · ${esc(d.enemy)}</div><h2>YOU DIED</h2><p>You lost $${d.cash}, ${d.xp} XP, ${d.respect} respect, all focus and ${d.items.length} carried items. Your level has reset to 1.</p><p>Your mission progress and moral choices remain. Lost story evidence is recorded in your journal; Paulie’s watch can be collected again from Eddie.</p><button class="primary danger" data-action="respawn">Respawn at St. Elzear’s</button></section>`;return;}

 if(state.ending){const e=G.endingText(state);el.innerHTML=`<div class="ending-banner"><div class="eyebrow">${e.subtitle}</div><h2>${e.title}</h2><p>Your choices shaped this ending. There are two other paths to discover.</p><button class="primary" data-action="ending">Read your epilogue</button> <button class="secondary" data-action="new">New story</button></div>`;return;}
 if(state.combat){renderCombat(el);return;}
 const d=G.dialogue(state);
 if(d){el.innerHTML=`<div class="dialogue-head"><canvas class="portrait" id="speaker" width="64" height="72"></canvas><div><div class="eyebrow">${G.people[d.who][1]}</div><h2>${G.people[d.who][0]}</h2></div><span class="turn-indicator">YOUR TURN</span></div><p class="dialogue-text">“${esc(d.text)}”</p><div class="choices">${d.choices.map((x,i)=>`<button class="choice" data-choice="${x.id}" ${x.enabled?'':'disabled'}><span class="number">${i+1}</span><span class="choice-label">${esc(x.text)}<small class="${x.tag.includes('COMPASSION')?'good':x.tag.includes('RUTHLESSNESS')?'bad':''}">${esc(x.tag)}${x.enabled?'':' · UNAVAILABLE'}</small></span><span class="arrow">›</span></button>`).join('')}</div>`;Scene.portrait($('#speaker'),d.who);return;}
 const loc=G.locations[state.location],info=G.roomInfo(state),here=G.nearbyPeople(state),others=loc.people.filter(id=>!here.includes(id));const outside=G.roomOf(state)==='exterior';el.innerHTML=`<div class="ambient-top"><span class="seal">${outside?'◇':'⌂'}</span><div><div class="eyebrow">${outside?'THE NEIGHBORHOOD':esc(loc.name.toUpperCase())}</div><h2>${esc(info.name)}</h2></div></div><p class="narrative">${state.stage===0&&state.location==='satriales'&&outside?'Tony has an errand for you. Talk to him outside, or step into the deli and look around.':esc(info.desc)}</p>${G.dangers(state).map(e=>`<section class="danger-card"><div class="eyebrow">ARMED ENCOUNTER · LETHAL RISK</div><h3>${esc(e.title)}</h3><p>${esc(e.desc)}</p><p>Victory: $${e.cash} + ${e.xp} XP. Death: lose all cash, XP, respect, focus and inventory.</p><button class="primary danger" data-encounter="${e.id}">Stand and fight</button><small>You can avoid this fight and continue your mission.</small></section>`).join('')}<div class="people-row">${here.map(id=>`<button class="person-button" data-talk="${id}"><span>◌</span>Approach ${esc(G.personLabel(state,id))}</button>`).join('')}${G.exits(state).map(id=>`<button class="person-button door-button" data-room="${id}"><span>↳</span>${esc(doorLabel(id))}</button>`).join('')}</div><p class="whereabouts">Select a person to walk over and speak. Introductions reveal names; conversations may offer directions.</p>`;

}
function renderCombat(el){const c=state.combat,sk=G.skills(state),info=G.combatInfo(state);el.innerHTML=`<div class="dialogue-head"><div><div class="eyebrow">LETHAL BATTLE · ROUND ${c.round}</div><h2>${esc(info.title)}</h2></div><span class="turn-indicator">FOCUS ${'◆'.repeat(state.focus)}${'◇'.repeat(3-state.focus)}</span></div><div class="combat-status"><div class="combatant"><b>Your health</b><span>${state.hp} / 100</span><div class="combat-bar"><i style="width:${state.hp}%"></i></div></div><div class="combatant"><b>${esc(info.enemy)} · Resolve</b><span>${c.enemy} / ${c.max}</span><div class="combat-bar"><i style="width:${c.enemy/c.max*100}%"></i></div></div></div><div class="enemy-intent">${c.won?'THREAT NEUTRALIZED':`${c.round%3===0?'HEAVY ATTACK INCOMING':'ENEMY PREPARING TO FIRE'} · ${G.incomingDamage(state)} damage · ${Math.max(3,G.incomingDamage(state)-18)} if guarded`}<small>Zero health means death. All cash, XP, respect, focus and items are lost.</small></div><div class="combat-log">${c.log.slice(0,3).map(t=>`<p>${esc(t)}</p>`).join('')}</div>${c.won?`<div class="choices"><button class="choice" data-resolve="mercy"><span class="number">1</span><span class="choice-label">Let them walk. You got what you came for.<small class="good">COMPASSION +10</small></span></button><button class="choice" data-resolve="ruthless"><span class="number">2</span><span class="choice-label">Make an example of them.<small class="bad">RUTHLESSNESS +15 • +10 HEAT</small></span></button></div>`:`<div class="combat-actions"><button data-combat="reason" ${state.focus<1?'disabled':''}><b>1 · Feint</b><small>−${16+sk.persuasion*4} RESOLVE · 1 FOCUS</small></button><button data-combat="pressure"><b>2 · Fire</b><small>−${12+sk.nerve*4} RESOLVE · FREE</small></button><button data-combat="guard"><b>3 · Guard</b><small>−18 INCOMING DAMAGE · +1 FOCUS</small></button><button data-combat="companion" ${c.companionUsed?'disabled':''}><b>4 · ${state.companion==='silvio'?'Counsel':state.companion==='chris'?'Backup':'Distraction'}</b><small>CREW ABILITY · ONCE PER FIGHT</small></button></div><button class="text-button" data-combat="retreat">Retreat to St. Elzear’s ↗</button>`}`;}
function renderJournal(){const completed=Object.entries(G.sideInfo).filter(([id])=>state.side[id]==='done').length;$('#journal-view').innerHTML=`<div class="eyebrow">EVERY FAVOR. EVERY CONSEQUENCE.</div><h1>Your journal</h1><div class="journal-columns"><div><h2 class="journal-heading">The main story</h2>${G.quests.map((q,i)=>i<=state.stage?`<div class="journal-item ${i===state.stage?'active':'done'}"><div class="eyebrow">${i===state.stage?'CURRENT OBJECTIVE':'✓ COMPLETED'} · CHAPTER ${i+1}</div><h3>${q[0]}</h3><p>${q[1]}</p>${i===state.stage&&!state.ending?'<button class="text-button" data-action="world">Return to the world ↗</button>':''}</div>`:'').join('')}<h2 class="journal-heading">Side jobs · ${completed} / 4 complete</h2>${Object.entries(G.sideInfo).map(([id,q])=>`<div class="journal-item ${state.side[id]==='done'?'done':''}"><div class="eyebrow">${state.side[id]==='done'?'✓ COMPLETED':state.side[id]==='active'?'IN PROGRESS':'AVAILABLE'} · ${G.locations[q[2]].name}</div><h3>${q[0]}</h3><p>${q[1]}</p></div>`).join('')}</div><div><h2 class="journal-heading">The story so far</h2>${state.history.length?state.history.map(t=>`<div class="history-item">${esc(t)}</div>`).join(''):'<p class="narrative">Your story starts with a conversation.</p>'}</div></div>`;}
function renderCharacter(){const sk=G.skills(state);$('#character-view').innerHTML=`<div class="eyebrow">YOU ARE WHAT YOU DO</div><h1>${G.classes[state.role].name}</h1><div class="character-grid"><section class="stat-card"><h2>Your reputation</h2><p>Every 100 XP increases all three skills. Skill checks are deterministic: meet the requirement and you succeed.</p><div class="stat-row"><span>Level</span><strong>${1+Math.floor(state.xp/100)}</strong></div><div class="stat-row"><span>Experience</span><strong>${state.xp} XP</strong></div>${['persuasion','nerve','business'].map(k=>`<div class="stat-row"><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${sk[k]}</strong></div>`).join('')}<div class="stat-row"><span>Health / Focus</span><strong>${state.hp} / ${state.focus}</strong></div></section><section class="stat-card"><h2>The life you choose</h2><p>Compassion is positive; ruthlessness is negative. Your final score determines your ending: +25 or higher, redemption; −25 or lower, empire; everything between, purgatory.</p><div class="stat-row"><span>Morality</span><strong>${state.morality>0?'+':''}${state.morality}</strong></div><div class="stat-row"><span>Respect</span><strong>${state.respect}</strong></div><div class="stat-row"><span>Heat</span><strong>${state.heat}%</strong></div><p style="margin-top:16px">Heat makes enemies hit harder. Respect records your standing in the family. Neither overrides the morality of your choices.</p></section><section class="stat-card"><h2>Your crew</h2><p>Silvio: 14 resolve damage and +2 focus. Paulie: 22 damage and guard. Christopher: 28 damage and guard. Each ability can be used once per confrontation.</p><div class="crew-select">${['silvio','paulie','chris'].map(id=>`<button data-companion="${id}" class="${state.companion===id?'selected':''}" ${state.death||state.combat||state.dialog||state.ending?'disabled':''}>${G.people[id][0].split(' ')[0]} ${state.companion===id?'✓':''}</button>`).join('')}</div></section><section class="stat-card"><h2>Your pockets</h2><div class="inventory-item">Cash · $${state.cash}</div>${state.inventory.map(t=>`<div class="inventory-item">◇ &nbsp; ${esc(t)}</div>`).join('')||'<p style="margin-top:15px">No quest items yet.</p>'}</section></div>`;}
function intro(){role='fixer';music.select('title','exterior','explore');if(soundOn)$('#sound').title=music.title();modal(`<div class="eyebrow">NEW JERSEY · 1999</div><h2 class="intro-masthead" id="modal-title">THE SOPRANOS<span>.</span></h2><div class="intro-sub">MADE IN JERSEY</div><p class="modal-intro">You’re on the edge of the family. One collection, one favor, one bad decision away from becoming somebody.<br>What kind of somebody is up to you.</p><button class="secondary title-music" data-action="sound" aria-pressed="${soundOn}">${soundOn?'Mute title music':'♪ Play title music'}</button><p class="save-note">Turnpike After Dark · Original 16-bit blues</p><div class="section-label" style="margin-bottom:14px">CHOOSE YOUR BACKGROUND</div><div class="role-grid">${Object.entries(G.classes).map(([id,r],i)=>`<button data-role="${id}" aria-pressed="${id===role}" class="role-option ${id===role?'selected':''}"><span class="role-icon">${['♧','♜','♢'][i]}</span><strong>${r.name}</strong><p>${r.desc}</p><small>${id==='fixer'?'PERSUASION':id==='soldier'?'NERVE':'BUSINESS'} +3</small></button>`).join('')}</div><div class="intro-meta"><span>3 ACTS</span><span>6 LOCATIONS</span><span>4 SIDE JOBS</span><span>3 ENDINGS</span></div><div class="modal-actions">${saved?'<button class="primary" data-action="continue">Continue your story</button>':''}<button class="${saved?'secondary':'primary'}" data-action="begin">${saved?'Start a new story':'Enter the neighborhood'} &nbsp; →</button></div><p class="save-note">A compact, original fan RPG. Choices have consequences. Progress saves on this device.</p>`);}
function start(){state=G.fresh(role);state.started=true;state.history=['You arrived at Satriale’s looking for a place in the family.'];$('#modal').close();setView('world');save();toast('Talk to Tony to begin. Your choices are final once selected.');}
function travel(){if(state.dialog||state.combat){toast('Finish this conversation or confrontation before traveling.');return;}if(state.ending||state.death)return;Scene.cancelApproach();modal(`${modalTitle('Somewhere in Jersey')}<p class="modal-intro">Same streets. Different business.</p><div class="travel-grid">${Object.entries(G.locations).map(([id,l])=>`<button class="location-card ${state.location===id?'current':''}" data-travel="${id}" ${id==='hotel'&&state.stage<7?'disabled':''}><span class="eyebrow">${l.district}</span><span class="card-mark">${id==='hotel'&&state.stage<7?'LOCKED':state.location===id?'YOU ARE HERE':'↗'}</span><strong>${l.name}</strong><p>${id==='hotel'&&state.stage<7?'Unlocks in the final chapter.':l.tag}</p></button>`).join('')}</div>`);}
function help(moral=false){modal(`${modalTitle(moral?'The life you choose':'Welcome to the neighborhood')}<div class="help-list">${moral?'<p><b>Compassion</b> means protecting people even when it costs you. <b>Ruthlessness</b> means using them to get ahead.</p><p>Choices move a score between −100 and +100. The final decision adds to your history; it does not erase it.</p><p><b>+25 or above:</b> Redemption.<br><b>−25 or below:</b> Empire.<br><b>Between:</b> Purgatory.</p><p>Side quests count. The journal remembers what you did. Your character page shows the exact score.</p>':'<p><b>Explore:</b> Click the ground to move. Select a person to walk over and talk when you are close enough. Click the ground to cancel the approach. People are described by appearance until you meet them. There are no quest markers above characters; ask around for directions. Click a labeled door or use the room navigation to enter buildings and back rooms. Inside, your character walks around solid furniture. Magnifying-glass markers let you inspect objects. E enters the next room; B goes back. Travel using the lower-right button or M.</p><p><b>Choose:</b> Dialogue waits for you. Press 1–6 or click a response. Muted options require more money, skills, or a quest item. A choice cannot be undone except by loading a manual save.</p><p><b>Confront:</b> Lower enemy resolve to zero. Feint spends focus, Fire is free, and Guard restores focus and reduces incoming damage by 18. Every third enemy turn is a heavy attack; check the intent warning before acting. Your companion gets one special move per fight. Every action triggers an enemy response unless you win.</p><p><b>Recover:</b> Rest at St. Elzear’s for free, or eat at Vesuvio. At zero health you die and lose every dollar, all XP and respect, all focus, and every carried item. Respawn at the church with full health but empty pockets. Mission progress and morality persist. Rest at the church for free focus recovery. Armed encounters can be retried until won.</p><p><b>Progress:</b> The active mission guides the main story. Side jobs improve your skills and affect the ending. Press J for journal, C for character, or Escape to close a panel.</p>'}</div><div class="modal-actions"><button class="primary" data-action="close">Understood</button></div>`);}
function settings(){modal(`${modalTitle('A moment to yourself')}<p class="modal-intro">Your progress saves automatically after every decision. A manual save lets you keep a point to return to.</p><div class="modal-actions"><button class="primary" data-action="manual-save">Save checkpoint</button><button class="secondary" data-action="load" ${manual?'':'disabled'}>Load checkpoint</button><button class="secondary danger" data-action="new">New story</button></div><p class="save-note">${storageOK?'Saves are stored in this browser on this device.':'Browser storage is unavailable. Keep this tab open to preserve this session.'}</p>`);}
function confirmNew(){modal(`${modalTitle('Start over?')}<p class="modal-intro">Starting a new story replaces your autosave. Your manual checkpoint will remain available.</p><div class="modal-actions"><button class="primary danger" data-action="new-confirm">Choose a new background</button><button class="secondary" data-action="close">Keep playing</button></div>`);}
function ending(){const e=G.endingText(state);const outcomes=[state.flags.annaSafe?'Anna leaves town safely. For her, that is enough.':state.flags.annaPromise?'Anna has your promise. Only time will tell what it is worth.':'Anna stays in the family’s shadow, keeping books she wishes she had never opened.',state.flags.artieHelp?'Artie keeps a table for you. Some debts never need collecting.':'Artie keeps his restaurant open. He no longer asks you how your day was.',state.flags.rosaHelp?'Rosa and her son stay in their apartment. The heat works now.':state.side.rosa==='done'?'Rosa learns that every kind of protection comes with a price.':'Rosa’s problems remain someone else’s business.',state.flags.chrisHelp?'Christopher keeps writing. There might be another life in those pages.':state.side.chris==='done'?'Christopher puts the script in a drawer and answers another call.':'Christopher’s unfinished script sits on a passenger seat.'];modal(`${modalTitle('The morning after')}<div class="ending-hero"><div class="ending-symbol">${state.ending==='redemption'?'♧':state.ending==='empire'?'♜':'◇'}</div><div class="eyebrow">${e.subtitle}</div><h1>${e.title}</h1><p>${e.text}</p><div class="ending-score">MORALITY ${state.morality>0?'+':''}${state.morality} &nbsp; · &nbsp; ${Object.values(state.side).filter(x=>x==='done').length}/4 SIDE JOBS &nbsp; · &nbsp; ${state.xp} XP</div></div>${outcomes.map(t=>`<p class="epilogue">${t}</p>`).join('')}<p class="save-note">Your accumulated morality determined this ending. Try a different background and different choices to discover the other two.</p><div class="modal-actions"><button class="primary" data-action="new">Play another life</button><button class="secondary" data-action="review-journal">Review your journal</button></div>`);}
async function toggleSound(){try{soundOn=await music.toggle();document.querySelectorAll('.title-music').forEach(b=>{b.textContent=soundOn?'Mute title music':'♪ Play title music';b.setAttribute('aria-pressed',String(soundOn));});$('#sound').style.color=soundOn?'var(--gold)':'';$('#sound').setAttribute('aria-label',soundOn?'Mute background music':'Enable background music');$('#sound').setAttribute('aria-pressed',String(soundOn));$('#sound').title=soundOn?music.title():'Enable original 16-bit music';toast(soundOn?'Now playing: '+music.title():'Music off');}catch(e){toast('Could not start music. Try the music button again.');}}
document.addEventListener('click',e=>{const b=e.target.closest('button,a.brand');if(!b||b.disabled)return;e.stopPropagation();if($('#modal').open&&!$('#modal').contains(b))return;
 if(b.matches('a.brand')){e.preventDefault();if(state.started)setView('world');return;}
 if(b.dataset.view){if(state.started)setView(b.dataset.view);return;}
 if(b.dataset.role){role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>{x.classList.toggle('selected',x.dataset.role===role);x.setAttribute('aria-pressed',String(x.dataset.role===role));});return;}
 if(b.dataset.room){changeRoom(b.dataset.room);return;}
 if(b.dataset.inspect!==undefined){inspectObject(b.dataset.inspect);return;}
 if(b.dataset.talk){approachPerson(b.dataset.talk);return;}
 if(b.dataset.choice){commit(()=>G.act(state,b.dataset.choice));return;}
 if(b.dataset.encounter){Scene.cancelApproach();commit(()=>G.beginEncounter(state,b.dataset.encounter));return;}
 if(b.dataset.combat){commit(()=>G.combatAct(state,b.dataset.combat));return;}
 if(b.dataset.resolve){commit(()=>G.resolveCombat(state,b.dataset.resolve==='mercy'));return;}
 if(b.dataset.travel){if(G.travel(state,b.dataset.travel)){closeModal();save();setView('world');}return;}
 if(b.dataset.companion){if(state.death||state.dialog||state.combat||state.ending)return;state.companion=b.dataset.companion;save();render();toast(G.people[state.companion][0]+' is riding with you.');return;}
 const action=b.dataset.action||b.id;
 switch(action){case 'respawn':commit(()=>G.respawn(state));break;case 'cancel-walk':Scene.cancelApproach();break;case 'show-conversation':$('#interaction').scrollIntoView({block:'start',behavior:'smooth'});break;case 'begin':if(saved&&state.started){confirmNew();}else if(saved){modal(`${modalTitle('Replace your autosave?')}<p class="modal-intro">Your current story will be replaced. Your manual checkpoint stays available.</p><div class="modal-actions"><button class="primary" data-action="start-confirm">Start new story</button><button class="secondary" data-action="intro">Go back</button></div>`);}else start();break;case 'start-confirm':start();break;case 'intro':intro();break;case 'continue':state=structuredClone(saved);$('#modal').close();setView('world');if(state.ending)ending();break;case 'new':confirmNew();break;case 'new-confirm':saved=null;intro();break;case 'close':closeModal();break;case 'travel-open':travel();break;case 'help':help();break;case 'morality-help':help(true);break;case 'settings':settings();break;case 'sound':toggleSound();break;case 'world':setView('world');break;case 'journal-open':setView('journal');break;case 'ending':ending();break;case 'review-journal':closeModal();setView('journal');break;
 case 'manual-save':try{localStorage.setItem(MANUAL,JSON.stringify(state));manual=structuredClone(state);toast('Checkpoint saved.');settings();}catch(e){toast('Storage unavailable. Your checkpoint could not be saved.');}break;
 case 'load':modal(`${modalTitle('Load your checkpoint?')}<p class="modal-intro">Decisions made after that checkpoint will be replaced.</p><div class="modal-actions"><button class="primary" data-action="load-confirm">Load checkpoint</button><button class="secondary" data-action="close">Cancel</button></div>`);break;
 case 'load-confirm':if(manual){state=structuredClone(manual);closeModal();save();setView('world');toast('Checkpoint restored.');if(state.ending)ending();}break;
 }
});
$('#modal').addEventListener('cancel',e=>{if(!state.started)e.preventDefault();});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||$('#modal').open||!state.started||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if((k==='e'||k==='b')&&view==='world'){e.preventDefault();const r=G.roomOf(state);changeRoom(k==='b'?(r==='backroom'?'interior':'exterior'):(r==='exterior'?'interior':r==='interior'?'backroom':'interior'));}else if(k==='m'){e.preventDefault();travel();}else if(k==='j')setView(view==='journal'?'world':'journal');else if(k==='c')setView(view==='character'?'world':'character');else if(k==='escape')setView('world');else if(/^[1-6]$/.test(k)&&view==='world'){const options=[...document.querySelectorAll('#interaction .choice,#interaction .combat-actions button')];const b=options[Number(k)-1];if(b&&!b.disabled){e.preventDefault();b.click();}}});
window.onWalkCancel=()=>{$('#footer-tip').textContent='Nothing personal. Just choices.';document.querySelectorAll('[data-talk]').forEach(b=>b.removeAttribute('aria-pressed'));interactionStatus();};
window.canWalk=()=>view==='world'&&state.started&&!state.death&&!state.dialog&&!state.combat&&!state.ending&&!$('#modal').open;
render();intro();
})();
