/* Made in Jersey — deterministic, dependency-free game rules. */
(function(root){
'use strict';
const ambient=typeof module!=='undefined'?require('./ambient.js'):root.AmbientNPCs;
const locations = {
 satriales:{name:"Satriale’s",district:'KEARNY',tag:'The neighborhood remembers.',desc:'Coffee in paper cups. A slow afternoon. A favor that is never just a favor.',people:['tony','paulie'],color:'#b9533e'},
 vesuvio:{name:'Nuovo Vesuvio',district:'NEWARK',tag:'Everybody has a tab.',desc:'White tablecloths cover a lot of dirty business. Artie is waiting by the kitchen.',people:['artie','rosa'],color:'#b89b56'},
 bing:{name:'The Bada Bing',district:'LODI',tag:'Business in the back.',desc:'The neon stays on. Silvio keeps an eye on the door and another on the books.',people:['silvio','chris'],color:'#b45182'},
 docks:{name:'Port Newark',district:'THE WATERFRONT',tag:'Nothing moves for free.',desc:'A missing shipment. An empty manifest. Someone is getting paid twice.',people:['vinnie','eddie'],color:'#7a9d9e'},
 church:{name:'St. Elzear’s',district:'NORTH WARD',tag:'A little room for grace.',desc:'Beyond the traffic, the courtyard is quiet. A place to catch your breath.',people:['father','anna'],color:'#829783'},
 hotel:{name:'The Essex House',district:'DOWNTOWN',tag:'All debts come due.',desc:'One room. One ledger. No more errands. This is where you decide who you are.',people:['rinaldi'],color:'#a99778'}
};
// Each building has a connected street → public room → private room layout.
const rooms={
 satriales:{interior:{name:'The deli',tag:'Cold cuts. Hot gossip.',desc:'A glass meat counter, hanging salami, tiled walls and a battered register. The door at the rear leads to the room where the real business gets done.'},backroom:{name:'The back room',tag:'Keep it in the family.',desc:'Wood paneling, a green checkered tablecloth, cold coffee and a television nobody is really watching. A room for conversations that should stay private.'}},
 vesuvio:{interior:{name:'The dining room',tag:'An affordable elegance.',desc:'White linen, green marble columns and a painted Bay of Naples. Conversation drifts between the tables and the kitchen door.'},backroom:{name:'Artie’s kitchen',tag:'The chef has enough on his plate.',desc:'Stainless worktops, a crowded prep table and a stove that has been running all afternoon. Artie works beside the pass.'}},
 bing:{interior:{name:'The club',tag:'The evening show.',desc:'Colored lights follow two adult dancers in glittering stage outfits. A long bar and low cocktail tables sit in the gloom. Some people come for the music. Others come on business.'},backroom:{name:'The office & pool room',tag:'The other kind of business.',desc:'A green-felt pool table sits beneath a hanging lamp. Glass blocks, beer cases, a punching bag and Silvio’s desk crowd the back room.'}},
 docks:{interior:{name:'The warehouse',tag:'Count everything twice.',desc:'Pallets and wooden crates line a concrete loading floor. Workers keep an eye on the shipments. The dispatch office is at the rear.'},backroom:{name:'Dispatch office',tag:'Every load leaves a paper trail.',desc:'A wall of schedules, an old terminal and a desk buried in carbon copies. The hum of the port seeps through the walls.'}},
 church:{interior:{name:'The sanctuary',tag:'A moment of quiet.',desc:'Rows of wooden pews face the altar. Candles flicker beneath stained glass. Father Matteo welcomes anyone who needs to sit down.'},backroom:{name:'The parish room',tag:'Some doors stay open.',desc:'A plain desk, donated groceries and a worn sofa. This small room gives the parish somewhere to help its neighbors.'}},
 hotel:{interior:{name:'The lobby',tag:'Keep your voice down.',desc:'Brass lamps, a polished reception desk and deep red carpet. Guests drift between the reception desk and the private rooms.'},backroom:{name:'Rinaldi’s suite',tag:'No more middlemen.',desc:'Heavy curtains frame the city lights. A drinks cabinet and a leather sofa flank the table where Rinaldi has laid out his papers.'}}
};
function roomOf(s){return s.room||'exterior';}
function roomInfo(s){return roomOf(s)==='exterior'?{name:s.location==='church'?'The courtyard':s.location==='docks'?'The loading yard':'The street',tag:locations[s.location].tag,desc:locations[s.location].desc}:rooms[s.location][roomOf(s)];}
function npcRoom(s,id){if(ambient[id])return ambient[id].room;if(id==='tony')return s.stage===0?'exterior':'backroom';return {paulie:'interior',artie:'backroom',rosa:'interior',silvio:'backroom',chris:'interior',vinnie:'interior',eddie:'exterior',father:'interior',anna:'exterior',rinaldi:'backroom'}[id];}
function nearbyPeople(s){return [...locations[s.location].people,...Object.keys(ambient).filter(id=>ambient[id].location===s.location)].filter(id=>npcRoom(s,id)===roomOf(s));}
function exits(s){const r=roomOf(s);return r==='exterior'?['interior']:r==='interior'?['exterior','backroom']:['interior'];}
function moveRoom(s,id){if(!s.started||s.death||s.dialog||s.combat||s.ending||!exits(s).includes(id))return false;s.room=id;return true;}
function migrateSave(s){if(!validSave(s))return null;const copy=JSON.parse(JSON.stringify(s));if(copy.room===undefined){copy.room=copy.combat?(copy.combat.kind==='docks'?'interior':'backroom'):copy.dialog?(npcRoom(copy,copy.dialog==='tony_ask'?'tony':copy.dialog==='final'?'rinaldi':copy.dialog)||'exterior'):'exterior';}copy.death=copy.death||null;copy.deaths=copy.deaths||0;copy.met=copy.met||[];copy.ambientTopic=copy.ambientTopic??null;return copy;}
const people={tony:['Tony Soprano','THE BOSS'],paulie:['Paulie Gualtieri','OLD SCHOOL'],artie:['Artie Bucco','RESTAURATEUR'],rosa:['Rosa Bellini','A NEIGHBOR'],silvio:['Silvio Dante','CONSIGLIERE'],chris:['Christopher Moltisanti','SOLDIER'],vinnie:['Vinnie Caruso','DOCK FOREMAN'],eddie:['Eddie Russo','NIGHT WATCHMAN'],father:['Father Matteo','PARISH PRIEST'],anna:['Anna Conti','BOOKKEEPER'],rinaldi:['Frank Rinaldi','THE MIDDLEMAN']};
for(const [id,npc]of Object.entries(ambient))people[id]=[npc.name,npc.role];
function personLabel(s,id){return (s.met||[]).includes(id)?people[id][0]:ambient[id]?.label||({tony:'Man in a polo shirt',paulie:'Man with silver hair',artie:'Chef by the pass',rosa:'Woman waiting alone',silvio:'Man beside the desk',chris:'Young man in a tracksuit',vinnie:'Man with a work jacket',eddie:'Watchman near the gate',father:'Parish priest',anna:'Woman near the courtyard',rinaldi:'Man beside the papers'}[id]);}
const classes={fixer:{name:'The Fixer',desc:'Find the right words. Keep your hands clean.',persuasion:3,nerve:1,business:2},soldier:{name:'The Soldier',desc:'Stand your ground. Let your reputation talk.',persuasion:1,nerve:3,business:2},earner:{name:'The Earner',desc:'Read the numbers. Always find another angle.',persuasion:2,nerve:1,business:3}};
const quests=[
 ['A seat at the table','Meet Tony outside Satriale’s.'],['The collection','Find Artie at Nuovo Vesuvio and ask about the debt.'],['An envelope short','Return to Satriale’s and find Tony.'],['Missing in transit','Find Vinnie at Port Newark and recover the manifest.'],['Numbers don’t lie','Find Silvio at the Bada Bing and show him the manifest.'],['The bookkeeper','Find Anna in the courtyard at St. Elzear’s.'],['The last favor','Find Tony at Satriale’s and report on Rinaldi.'],['A room with a view','Find Rinaldi at the Essex House. Finish any side jobs first.'],['The morning after','Your story is complete.']
];
const sideInfo={rosa:['A little breathing room','Rosa needs help keeping her apartment.','vesuvio'],paulie:['The lost watch','Paulie’s watch was last seen at the docks.','satriales'],chris:['A different script','Christopher wants an honest opinion on his screenplay.','bing'],eddie:['The night shift','Eddie’s wages disappeared from the books.','docks']};
function fresh(role='fixer'){return {version:1,role,location:'satriales',room:'exterior',met:[],ambientTopic:null,stage:0,morality:0,hp:100,focus:3,cash:150,xp:0,respect:0,heat:0,companion:'silvio',flags:{},side:{},inventory:[],history:[],dialog:null,combat:null,ending:null,death:null,deaths:0,started:false,turn:0};}
function skills(s){const c=classes[s.role];const lv=Math.floor(s.xp/100);return {...c,persuasion:c.persuasion+lv,nerve:c.nerve+lv,business:c.business+lv};}
function note(s,t){s.history.unshift(t);s.history=s.history.slice(0,40);}
function reward(s,delta){for(const [k,v] of Object.entries(delta||{})){if(k==='flag')s.flags[v]=true;else if(k==='item'){if(!s.inventory.includes(v))s.inventory.push(v);}else s[k]+=v;}s.morality=Math.max(-100,Math.min(100,s.morality));s.cash=Math.max(0,s.cash);s.heat=Math.max(0,Math.min(100,s.heat));s.hp=Math.max(0,Math.min(100,s.hp));}
function choice(id,text,tag,run,enabled=true){return {id,text,tag,run,enabled};}
function next(s,n,text,effects){reward(s,effects);s.stage=n;s.dialog=null;note(s,text);}
function sideDone(s,key,text,effects){s.side[key]='done';if(key==='paulie')s.inventory=s.inventory.filter(item=>item!=='Paulie’s watch');reward(s,{xp:35,...effects});s.dialog=null;note(s,text);}
function say(who,text,choices){return {who,text,choices};}
function leave(){return choice('leave','We’ll talk later.','LEAVE',s=>{s.dialog=null;});}
const encounters={
 alley:{title:'The collection ambush',enemy:'Loan sharks',location:'vesuvio',room:'exterior',stage:1,hp:72,attack:18,cash:90,xp:40,desc:'Two loan sharks are waiting outside Artie’s restaurant. They want his envelope — and they are willing to kill for it.'},
 tail:{title:'A tail outside the Bing',enemy:'Rinaldi’s enforcers',location:'bing',room:'exterior',stage:4,hp:90,attack:20,cash:140,xp:55,desc:'A sedan has followed you from the docks. Rinaldi’s men step out and demand the manifest. Stand your ground and stop them following Anna.'},
 hitmen:{title:'The lobby hit',enemy:'Hotel gunmen',location:'hotel',room:'interior',stage:7,hp:100,attack:18,cash:200,xp:70,desc:'Rinaldi has posted gunmen by the elevators. Challenge them before meeting their boss, or slip through the service corridor.'}
};
function dangers(s){if(!s.started||s.death||s.dialog||s.combat||s.ending)return [];return Object.entries(encounters).filter(([id,e])=>s.location===e.location&&roomOf(s)===e.room&&s.stage>=e.stage&&!s.flags['won_'+id]).map(([id,e])=>({id,...e}));}
function beginEncounter(s,id){if(!dangers(s).some(e=>e.id===id))return false;startCombat(s,id);return true;}
function combatInfo(s){const c=s.combat;if(!c)return null;const e=encounters[c.kind];return {title:e?.title||(c.kind==='docks'?'Trouble at the docks':'The last stand'),enemy:e?.enemy||(c.kind==='docks'?'Vinnie’s crew':'Rinaldi’s bodyguard')};}
function incomingDamage(s){const c=s.combat;if(!c)return 0;return (encounters[c.kind]?.attack||(c.kind==='final'?20:18))+Math.floor(s.heat/20)+(c.round%3===0?12:0);}
function startCombat(s,kind){s.dialog=null;const e=encounters[kind],hp=e?.hp||(kind==='docks'?66:88);s.combat={kind,round:1,enemy:hp,max:hp,guard:false,companionUsed:false,log:[e?.desc||(kind==='docks'?'Vinnie’s crew draws weapons and blocks the loading bay.':'Rinaldi’s bodyguard opens fire from behind the desk.')],won:false};s.focus=3;}
function die(s){s.death={enemy:combatInfo(s).enemy,cash:s.cash,xp:s.xp,respect:s.respect,items:[...s.inventory]};s.deaths=(s.deaths||0)+1;s.hp=0;s.focus=0;s.cash=0;s.xp=0;s.respect=0;s.inventory=[];s.dialog=null;s.combat=null;note(s,'You died. All cash, XP, respect, focus and carried items were lost. Respawn at St. Elzear’s to continue.');}
function respawn(s){if(!s.death)return false;s.death=null;s.hp=100;s.focus=0;s.location='church';s.room='interior';note(s,'You respawned at St. Elzear’s with empty pockets. Rest to recover focus. Your choices and mission progress remain.');return true;}
function finishEnding(s,action){reward(s,action==='protect'?{morality:20}:action==='rule'?{morality:-20}:{morality:0});s.flags.finalAction=action;s.ending=s.morality>=25?'redemption':s.morality<=-25?'empire':'purgatory';s.stage=8;s.dialog=null;s.combat=null;note(s,'The last decision is made.');}
function dialogue(s){const id=s.dialog;if(!id)return null;const sk=skills(s);const back=leave();
 if(ambient[id]){const npc=ambient[id],topic=Number.isInteger(s.ambientTopic)?npc.topics[s.ambientTopic]:null;return say(id,topic?topic[1]:npc.intro,[...npc.topics.map((t,i)=>choice('topic_'+i,t[0],'ASK',s=>{s.ambientTopic=i;})),back]);}
 switch(id){
 case 'tony':
 if(s.stage===0)return say(id,'You grew up around here. You know the faces. Now I need to know if I can trust you. Artie’s behind on an envelope. Go see him. How you handle it? That tells me something.',[choice('accept','I’ll talk to him.','BEGIN • THE COLLECTION',s=>next(s,1,'Tony asked you to collect Artie’s overdue envelope.')),choice('ask','What happens if he can’t pay?','ASK',s=>{s.dialog='tony_ask';}),back]);
 if(s.stage===2)return say(id,s.flags.artieHelp?'Artie says you gave him room to breathe. You found a way to keep him in business. Now let’s see if you can handle something bigger.':'The envelope came in. People are already talking about how you handled it. That’s the thing about this neighborhood.',[choice('report','What’s next?','COMPLETE • +60 XP',s=>next(s,3,'A shipment vanished at Port Newark. Tony wants the manifest.',{xp:60,respect:10,cash:100})),back]);
 if(s.stage===4)return say(id,s.inventory.includes('Shipping manifest')?'You got the manifest. Good. That takes care of the docks. Now take those numbers to Silvio at the Bada Bing — he’ll figure out who’s skimming off the shipments.':'You recovered the manifest at the docks. Losing the paperwork doesn’t erase what you found. Go over the shipment details with Silvio at the Bada Bing; he can still trace the missing money.',[choice('silvio','I’ll go over the numbers with Silvio.','NEXT LEAD • THE BADA BING',s=>{s.dialog=null;}),back]);
 if(s.stage===5)return say(id,'Silvio went through the manifest. You did your part at the docks. Now find Anna Conti at St. Elzear’s — she kept the books, and she can tell us where the money went.',[back]);
 if(s.stage===6)return say(id,'Rinaldi’s been shaving money off every truck, then putting my name on the shortfall. He’s at the Essex House tonight. Bring me that ledger. And think carefully about what kind of future you want.',[choice('accept','I’ll settle it.','FINAL MISSION • +60 XP',s=>next(s,7,'Rinaldi is waiting at the Essex House. There is no going back after the final decision.',{xp:60,respect:10})),back]);
 return say(id,({1:'Artie’s envelope is still outstanding. Find him at Nuovo Vesuvio and work it out.',3:'We still need that shipping manifest. Find Vinnie at Port Newark and get the paperwork.',7:'You uncovered the missing shipments and found the bookkeeper. Now settle things with Rinaldi at the Essex House and get the original ledger.'})[s.stage]||'You handled the business. The neighborhood will remember how you did it.',[back]);
 case 'tony_ask':return say('tony','There’s collecting a debt, and there’s making an enemy. Don’t confuse the two. But don’t come back empty-handed, either.',[choice('accept','Understood. I’ll find a way.','BEGIN • THE COLLECTION',s=>next(s,1,'Tony asked you to collect Artie’s overdue envelope.')),back]);
 case 'artie':
 if(s.stage===1)return say(id,'The freezer died. Then the supplier wanted cash. I can give you a hundred now, but the rest… you know me. This place is everything I’ve got.',[
 choice('help','Cover the shortfall yourself. Let Artie keep the restaurant running.','COMPASSION +20 • −$100',s=>next(s,2,'You covered Artie’s debt. He will remember it.',{morality:20,cash:-100,xp:40,flag:'artieHelp'}),s.cash>=100),
 choice('plan','Work out a payment schedule he can actually afford.','PERSUASION 3 • COMPASSION +10',s=>next(s,2,'Artie agreed to a workable payment schedule.',{morality:10,xp:40,flag:'artieHelp'}),sk.persuasion>=3),
 choice('collect','Take what he has. Give him one more week.','BUSINESS • +$50',s=>next(s,2,'You took a partial payment and gave Artie a week.',{cash:50,xp:40})),
 choice('threaten','Make it clear the restaurant is collateral.','RUTHLESSNESS +20 • +$150',s=>next(s,2,'Artie paid in full, at a cost to the neighborhood.',{morality:-20,cash:150,xp:40,heat:10,respect:5})),back]);
 return say(id,s.flags.artieHelp?'You kept this place open. There’s always a table here for you.':'I’m trying to keep a restaurant running. Some days, that’s all I can do.',[choice('meal','Sit down for a meal. Restore health and focus. ',s.flags.artieHelp?'ON THE HOUSE':'−$35',s=>{reward(s,{cash:s.flags.artieHelp?0:-35});s.hp=100;s.focus=3;s.dialog=null;note(s,'A hot meal restored your health and focus.');},s.flags.artieHelp||s.cash>=35),back]);
 case 'silvio':
 if(s.stage===4)return say(id,'These numbers aren’t mistakes. The same account gets a cut from every shipment. Anna Conti kept those books. Find her at the church before Rinaldi does.',[choice('investigate','I’ll find Anna.','COMPLETE • +75 XP',s=>next(s,5,'Silvio traced the missing money to Rinaldi. Anna Conti has the evidence.',{xp:75,cash:125,respect:10})),back]);
 return say(id,'People tell you what they want you to hear. Listen for what they leave out. And remember: you can win a confrontation without throwing a punch.',[choice('companion','Come with me. I could use your advice.','COMPANION • RESTORE FOCUS',s=>{s.companion='silvio';s.dialog=null;note(s,'Silvio joined you. His Counsel restores 2 focus in a confrontation.');}),back]);
 case 'vinnie':
 if(s.stage===3)return say(id,'Manifest? Never saw it. Look, my guys don’t like strangers hanging around. Pay the handling fee, or get moving.',[
 choice('reason','The books don’t add up. Hand it over before you take the blame.','PERSUASION 3 • COMPASSION +10',s=>next(s,4,'Vinnie surrendered the manifest without a fight.',{xp:60,morality:10,item:'Shipping manifest'}),sk.persuasion>=3),
 choice('bribe','Pay the handling fee.','−$100',s=>next(s,4,'You bought the shipping manifest.',{xp:60,cash:-100,item:'Shipping manifest'}),s.cash>=100),
 choice('fight','We’re not leaving without that manifest.','TURN-BASED CONFRONTATION',s=>startCombat(s,'docks')),back]);
 return say(id,s.stage>3?'You got your paperwork. We’re done here.':'Private dock. No deliveries today.',[back]);
 case 'anna':
 if(s.stage===5)return say(id,'I copied the ledger. Names, transfers, everything. Rinaldi found out. If I give you this, do I make it out of here? I need more than a promise.',[
 choice('protect','Arrange a safe ride for her. The family doesn’t need her name.','COMPASSION +25 • −$75',s=>next(s,6,'You protected Anna and secured her copy of the ledger.',{morality:25,cash:-75,xp:60,item:'Copied ledger',flag:'annaSafe'}),s.cash>=75),
 choice('parish','Ask Father Matteo to shelter her.','REQUIRES PARISH DONATION • COMPASSION +25',s=>next(s,6,'The parish sheltered Anna. She gave you the copied ledger.',{morality:25,xp:60,item:'Copied ledger',flag:'annaSafe'}),!!s.flags.parish),
 choice('deal','Trade the ledger for your word that you’ll keep her out of it.','COMPASSION +5',s=>next(s,6,'Anna trusted your promise and handed over the copied ledger.',{morality:5,xp:60,item:'Copied ledger',flag:'annaPromise'})),
 choice('force','Take the ledger. Tell her she answers to the family now.','RUTHLESSNESS +25 • +10 RESPECT',s=>next(s,6,'You took the ledger and put Anna under the family’s control.',{morality:-25,xp:60,respect:10,heat:15,item:'Copied ledger'})),back]);
 return say(id,s.flags.annaSafe?'For the first time in weeks, I think I might sleep tonight. Thank you.':'I’m waiting for someone. Please don’t make a scene.',[back]);
 case 'father':return say(id,'You can sit here for as long as you need. What you do when you leave is up to you.',[
 choice('rest','Take a quiet moment.','RESTORE HEALTH & FOCUS • FREE',s=>{s.hp=100;s.focus=3;s.dialog=null;note(s,'A quiet moment at St. Elzear’s restored you.');}),
 ...(!s.flags.parish?[choice('donate','Help the parish emergency fund.','−$50 • COMPASSION +10',s=>{reward(s,{cash:-50,morality:10,flag:'parish'});s.dialog=null;note(s,'The parish can now shelter someone in need.');},s.cash>=50)]:[]),back]);
 case 'rosa':
 if(s.side.rosa==='done')return say(id,s.flags.rosaHelp?'The landlord fixed the heat. My little boy slept through the night. I won’t forget what you did.':'I found somewhere else. I guess that’s what people do.',[back]);
 return say(id,'The landlord wants another deposit. The heat hasn’t worked in a month. I don’t need trouble. I just need somebody to listen.',[
 choice('pay','Cover the deposit and call the landlord.','SIDE QUEST • −$60 • COMPASSION +15',s=>sideDone(s,'rosa','You kept Rosa and her son in their home.',{cash:-60,morality:15,flag:'rosaHelp'}),s.cash>=60),
 choice('persuade','Use the housing code to get the landlord to back down.','BUSINESS 3 • COMPASSION +15',s=>sideDone(s,'rosa','You helped Rosa challenge an unlawful deposit.',{morality:15,flag:'rosaHelp'}),sk.business>=3),
 choice('exploit','Offer protection—for a monthly fee.','SIDE QUEST • +$80 • RUTHLESSNESS +15',s=>sideDone(s,'rosa','Rosa’s rent problem became a protection payment.',{cash:80,morality:-15,heat:5})),back]);
 case 'paulie':
 if(s.side.paulie==='done')return say(id,'That watch had history. People don’t care about history anymore. You did alright.',[choice('companion','Ride with me, Paulie.','COMPANION • DISTRACTION',s=>{s.companion='paulie';s.dialog=null;note(s,'Paulie joined you. His Distraction lowers enemy resolve by 22.');}),back]);
 if(s.inventory.includes('Paulie’s watch'))return say(id,'There it is. Not a scratch. Where’d you find it? Actually, don’t tell me. Some things I don’t need to know.',[choice('return','Give Paulie his watch.','COMPLETE • +$80 • +35 XP',s=>sideDone(s,'paulie','You returned Paulie’s watch.',{cash:80,respect:8})),back]);
 return say(id,'I left a watch down at the docks. Silver band. Sentimental value. Find it, bring it back, and we’ll call it a good day.',[choice('accept','I’ll ask around the docks.','SIDE QUEST • THE LOST WATCH',s=>{s.side.paulie='active';s.dialog=null;note(s,'Paulie lost his watch at Port Newark. Ask Eddie.');}),choice('companion','Come along. You can help me look.','COMPANION • DISTRACTION',s=>{s.side.paulie='active';s.companion='paulie';s.dialog=null;note(s,'Paulie joined you to find his watch.');}),back]);
 case 'eddie':
 if(s.side.paulie==='active'&&!s.inventory.includes('Paulie’s watch'))return say(id,'Silver watch? Found it by the loading bay. Kept it safe. I don’t want to owe anybody anything.',[choice('watch','Take the watch. Thank him for looking after it.','QUEST ITEM • PAULIE’S WATCH',s=>{reward(s,{item:'Paulie’s watch'});s.dialog=null;note(s,'Eddie returned Paulie’s watch. Bring it to Paulie.');}),back]);
 if(s.side.eddie==='done')return say(id,s.flags.eddieHelp?'My wages came through. I can stop working doubles.':'I got the message. I’ll keep my head down.',[back]);
 return say(id,'Three weeks I’ve worked without a check. They say it’s an accounting problem. Funny how the problem never touches the guys upstairs.',[
 choice('help','Get the missing wages released.','BUSINESS 3 OR MANIFEST • COMPASSION +15',s=>sideDone(s,'eddie','You used the books to recover Eddie’s missing wages.',{morality:15,cash:40,flag:'eddieHelp'}),sk.business>=3||s.inventory.includes('Shipping manifest')),
 choice('pay','Pay him enough to get through the week.','−$50 • COMPASSION +10',s=>sideDone(s,'eddie','You helped Eddie get through the week.',{cash:-50,morality:10,flag:'eddieHelp'}),s.cash>=50),
 choice('cut','Get his wages released, but keep a finder’s fee.','+$100 • RUTHLESSNESS +15',s=>sideDone(s,'eddie','You took a cut of Eddie’s overdue pay.',{cash:100,morality:-15})),back]);
 case 'chris':
 if(s.side.chris==='done')return say(id,s.flags.chrisHelp?'I rewrote the ending. Turns out the guy doesn’t have to be a gangster forever.':'Maybe you’re right. Maybe the movie thing was never going anywhere.',[choice('companion','Let’s take a ride.','COMPANION • BACKUP',s=>{s.companion='chris';s.dialog=null;note(s,'Christopher joined you. His Backup lowers enemy resolve by 28.');}),back]);
 return say(id,'I got thirty pages. Guy from Jersey wants something bigger, but everybody keeps dragging him back. Be honest. Is there a movie in that?',[
 choice('support','There is. Finish it. Give yourself something outside this life.','SIDE QUEST • COMPASSION +10',s=>sideDone(s,'chris','You encouraged Christopher to finish his screenplay.',{morality:10,flag:'chrisHelp'})),
 choice('sell','The story needs work, but I know a guy who’ll read it.','BUSINESS 3 • +$50',s=>sideDone(s,'chris','You found a producer willing to read Christopher’s screenplay.',{cash:50,flag:'chrisHelp'}),sk.business>=3),
 choice('mock','Forget the movies. You’re useful where you are.','SIDE QUEST • RUTHLESSNESS +10',s=>sideDone(s,'chris','You pushed Christopher deeper into the family business.',{morality:-10,respect:5})),back]);
 case 'rinaldi':
 if(s.stage!==7)return say(id,'You don’t have an appointment.',[back]);
 if(s.flags.finalWon)return finalDialogue(s);
 return say(id,'Tony sent you? Of course he did. You’ve been carrying envelopes while I’ve been moving real money. There’s room on my side of the table. Or we can make this difficult.',[
 choice('evidence','I have Anna’s copy. Your leverage is gone. Hand over the original.','PERSUASION 5 • AVOID CONFRONTATION',s=>{reward(s,{item:'Original ledger'});s.flags.finalWon=true;s.dialog='final';},sk.persuasion>=5),
 choice('buy','Buy the original ledger. End this quietly.','−$250 • AVOID CONFRONTATION',s=>{reward(s,{cash:-250});reward(s,{item:'Original ledger'});s.flags.finalWon=true;s.dialog='final';},s.cash>=250),
 choice('confront','No deal. Put the ledger on the table.','FINAL CONFRONTATION',s=>startCombat(s,'final')),back]);
 case 'final':return finalDialogue(s);
 default:return null;
 }
}
function finalDialogue(s){return say('rinaldi','Alright. The ledger is yours. Give it to Tony and nothing changes. Use it yourself and you could run this town. Or destroy the whole arrangement. You’ve made your choices all week. Who are you now?',[
 choice('protect','Expose the scheme through a lawyer and get the witnesses to safety.','COMPASSION +20 • END THE STORY',s=>finishEnding(s,'protect')),
 choice('loyal','Give Tony the ledger. Keep your seat at the table.','LOYALTY • END THE STORY',s=>finishEnding(s,'loyal')),
 choice('rule','Keep the ledger. Make the family answer to you.','RUTHLESSNESS +20 • END THE STORY',s=>finishEnding(s,'rule'))]);}
function act(s,id){if(s.death)return false;const d=dialogue(s);const c=d?.choices.find(c=>c.id===id);if(!c||!c.enabled)return false;c.run(s);s.turn++;return true;}
function travel(s,id){if(!locations[id]||s.death||s.dialog||s.combat||s.ending||(!s.started)||id==='hotel'&&s.stage<7)return false;s.location=id;s.room='exterior';return true;}
function talk(s,id){if(s.death||s.dialog||s.combat||s.ending||!s.started||!nearbyPeople(s).includes(id))return false;s.dialog=id;s.ambientTopic=null;s.met=s.met||[];if(!s.met.includes(id))s.met.push(id);return true;}
function combatAct(s,id){const c=s.combat;if(!c||c.won)return false;const sk=skills(s);let damage=0;let msg='';let guard=false;
 if(id==='reason'){if(s.focus<1)return false;s.focus--;damage=16+sk.persuasion*4;msg='You feint and strike while they are exposed.';}
 else if(id==='pressure'){damage=12+sk.nerve*4;msg='You fire from cover.';}
 else if(id==='guard'){s.focus=Math.min(3,s.focus+1);guard=true;damage=5;msg='You keep your guard up and recover 1 focus.';}
 else if(id==='companion'){if(c.companionUsed)return false;c.companionUsed=true;if(s.companion==='silvio'){s.focus=Math.min(3,s.focus+2);damage=14;msg='Silvio finds an opening. +2 focus.';}else{damage=s.companion==='chris'?28:22;msg=s.companion==='chris'?'Christopher backs you up.':'Paulie draws their attention.';guard=true;}}
 else if(id==='retreat'){s.location='church';s.room='interior';s.combat=null;note(s,'You backed off. Recover at the church and try another approach.');return true;}else return false;
 c.enemy=Math.max(0,c.enemy-damage);c.log.unshift(msg+' −'+damage+' resolve.');
 if(c.enemy===0){c.won=true;c.log.unshift('The attackers are disarmed. You decide how this ends.');return true;}
 const incoming=Math.max(3,incomingDamage(s)-(guard?18:0));s.hp=Math.max(0,s.hp-incoming);c.log.unshift('They retaliate. −'+incoming+' health.');c.round++;s.turn++;
 if(s.hp===0)die(s);return true;
}
function resolveCombat(s,mercy){const c=s.combat;if(!c?.won)return false;reward(s,mercy?{morality:10}:{morality:-15,heat:10,respect:5});s.combat=null;if(encounters[c.kind]){const e=encounters[c.kind];s.flags['won_'+c.kind]=true;reward(s,{cash:e.cash,xp:e.xp});note(s,e.title+' survived. Recovered $'+e.cash+' and earned '+e.xp+' XP.');return true;}if(c.kind==='docks')next(s,4,mercy?'You let Vinnie walk and recovered the manifest.':'You made an example of Vinnie and recovered the manifest.',{xp:60,item:'Shipping manifest'});else{reward(s,{item:'Original ledger'});s.flags.finalWon=true;s.dialog='final';note(s,mercy?'You let the bodyguard leave.':'You made sure the bodyguard would remember you.');}return true;}
function endingText(s){const endings={redemption:{title:'A way out',subtitle:'THE REDEMPTION ENDING',text:'You spent a lifetime learning what this neighborhood demanded. In the end, you learned what you could refuse. The people you protected become something more valuable than an organization: a life beyond it.'},empire:{title:'The new management',subtitle:'THE EMPIRE ENDING',text:'You get the best table. Your calls are always answered. Men who used to laugh at you lower their voices when you enter. You wanted a place in the family. Now the family has a place beneath you.'},purgatory:{title:'Same table. Same life.',subtitle:'THE PURGATORY ENDING',text:'The envelopes keep arriving. The coffee goes cold. You did enough good to sleep some nights, and enough harm to stay useful. Tomorrow the phone will ring. You already know you will answer.'}};return endings[s.ending];}
function validSave(x){return !!(x&&x.version===1&&(x.deaths===undefined||Number.isInteger(x.deaths)&&x.deaths>=0)&&(x.death===undefined||x.death===null||typeof x.death.enemy==='string'&&['cash','xp','respect'].every(k=>Number.isFinite(x.death[k])&&x.death[k]>=0)&&Array.isArray(x.death.items)&&x.death.items.every(i=>typeof i==='string')&&x.hp===0&&x.combat===null&&x.dialog===null)&&(x.met===undefined||Array.isArray(x.met)&&x.met.every(id=>typeof id==='string'&&!!people[id]))&&(x.ambientTopic===undefined||x.ambientTopic===null||Number.isInteger(x.ambientTopic)&&x.ambientTopic>=0&&x.ambientTopic<2)&&(x.room===undefined||['exterior','interior','backroom'].includes(x.room))&&classes[x.role]&&locations[x.location]&&Number.isInteger(x.stage)&&x.stage>=0&&x.stage<=8&&['morality','hp','focus','cash','xp','respect','heat','turn'].every(k=>Number.isFinite(x[k]))&&x.morality>=-100&&x.morality<=100&&x.hp>=0&&x.hp<=100&&x.cash>=0&&x.xp>=0&&x.focus>=0&&x.focus<=3&&['silvio','paulie','chris'].includes(x.companion)&&x.flags&&typeof x.flags==='object'&&!Array.isArray(x.flags)&&x.side&&typeof x.side==='object'&&!Array.isArray(x.side)&&Object.values(x.side).every(v=>['active','done'].includes(v))&&Array.isArray(x.inventory)&&x.inventory.every(v=>typeof v==='string')&&Array.isArray(x.history)&&x.history.every(v=>typeof v==='string')&&typeof x.started==='boolean'&&(x.dialog===null||people[x.dialog]||['tony_ask','final'].includes(x.dialog))&&(x.ending===null||['redemption','empire','purgatory'].includes(x.ending))&&(x.combat===null||(['docks','final',...Object.keys(encounters)].includes(x.combat.kind)&&Number.isFinite(x.combat.enemy)&&Number.isFinite(x.combat.round)&&Array.isArray(x.combat.log)&&x.combat.log.every(v=>typeof v==='string'))));}
const API={encounters,dangers,beginEncounter,combatInfo,incomingDamage,respawn,ambient,personLabel,rooms,roomOf,roomInfo,npcRoom,nearbyPeople,exits,moveRoom,migrateSave,locations,people,classes,quests,sideInfo,fresh,skills,dialogue,act,travel,talk,combatAct,resolveCombat,endingText,validSave};if(typeof module!=='undefined')module.exports=API;root.Game=API;
})(typeof window!=='undefined'?window:globalThis);
