const {test}=require('node:test');
const assert=require('node:assert/strict');
const G=require('../engine.js');
function start(role='fixer'){const s=G.fresh(role);s.started=true;return s;}
function visit(s,loc,npc){assert.equal(G.travel(s,loc),true,`Travel to ${loc}`);const room=G.npcRoom(s,npc);if(room!=='exterior')assert.equal(G.moveRoom(s,'interior'),true);if(room==='backroom')assert.equal(G.moveRoom(s,'backroom'),true);assert.equal(G.talk(s,npc),true,`Talk to ${npc}`);}
function choose(s,id){assert.equal(G.act(s,id),true,`Choice ${id} from ${s.dialog}`);assert.ok(G.validSave(JSON.parse(JSON.stringify(s))),'State survives save round trip');}
function advance(s,path='good'){
 visit(s,'satriales','tony');choose(s,'accept');
 visit(s,'vesuvio','artie');choose(s,path==='good'?'help':path==='evil'?'threaten':'collect');
 visit(s,'satriales','tony');choose(s,'report');
 visit(s,'docks','vinnie');choose(s,path==='good'&&G.skills(s).persuasion>=3?'reason':'bribe');
 visit(s,'bing','silvio');choose(s,'investigate');
 visit(s,'church','anna');choose(s,path==='good'?'protect':path==='evil'?'force':'deal');
 visit(s,'satriales','tony');choose(s,'accept');
 visit(s,'hotel','rinaldi');
 if(G.skills(s).persuasion>=5)choose(s,'evidence');else{choose(s,'confront');win(s);assert.equal(G.resolveCombat(s,path!=='evil'),true);}
}
function win(s){let n=0;while(s.combat&&!s.combat.won&&n++<20){G.combatAct(s,s.focus?'reason':'pressure');}assert.ok(s.combat?.won,'Encounter is winnable');}
for(const role of Object.keys(G.classes))for(const path of ['good','evil','neutral'])test(`${role}: complete ${path} campaign`,()=>{const s=start(role);advance(s,path);choose(s,path==='good'?'protect':path==='evil'?'rule':'loyal');assert.equal(s.stage,8);assert.ok(s.inventory.includes('Original ledger'));assert.equal(s.ending,path==='good'?'redemption':path==='evil'?'empire':'purgatory');assert.ok(G.endingText(s).text);assert.equal(G.travel(s,'satriales'),false);});
test('Side jobs resolve once, with persistent consequences and quest items',()=>{const s=start('earner');visit(s,'vesuvio','rosa');choose(s,'persuade');const xp=s.xp;G.talk(s,'rosa');assert.equal(G.act(s,'persuade'),false);assert.equal(s.xp,xp);choose(s,'leave');visit(s,'satriales','paulie');choose(s,'accept');visit(s,'docks','eddie');choose(s,'watch');assert.ok(s.inventory.includes('Paulie’s watch'));visit(s,'satriales','paulie');choose(s,'return');assert.ok(!s.inventory.includes('Paulie’s watch'));visit(s,'docks','eddie');choose(s,'help');visit(s,'bing','chris');choose(s,'support');assert.equal(Object.values(s.side).filter(v=>v==='done').length,4);assert.equal(s.xp,140);assert.ok(s.flags.rosaHelp&&s.flags.eddieHelp&&s.flags.chrisHelp);});
test('Unaffordable or unavailable choices never mutate state',()=>{const s=start('soldier');s.stage=1;s.location='vesuvio';s.room='backroom';s.cash=0;G.talk(s,'artie');for(const id of ['help','plan','not-a-choice']){const before=JSON.stringify(s);assert.equal(G.act(s,id),false);assert.equal(JSON.stringify(s),before);}assert.equal(G.travel(s,'church'),false);choose(s,'collect');});
test('Late location is locked and unknown characters cannot be summoned',()=>{const s=start();assert.equal(G.travel(s,'hotel'),false);assert.equal(G.travel(s,'unknown'),false);assert.equal(G.talk(s,'rinaldi'),false);});
test('Parish shelter is earned and donation cannot be farmed',()=>{const s=start();visit(s,'church','father');choose(s,'donate');const morality=s.morality;G.talk(s,'father');assert.equal(G.act(s,'donate'),false);choose(s,'leave');s.stage=5;s.cash=0;G.moveRoom(s,'exterior');G.talk(s,'anna');choose(s,'parish');assert.equal(s.morality,morality+25);assert.ok(s.flags.annaSafe);});
test('Dock combat: focus, companion limit, guard, victory, and mercy',()=>{const s=start('soldier');s.stage=3;s.location='docks';s.room='interior';G.talk(s,'vinnie');choose(s,'fight');s.focus=0;assert.equal(G.combatAct(s,'reason'),false);G.combatAct(s,'guard');assert.equal(s.focus,1);G.combatAct(s,'companion');assert.equal(G.combatAct(s,'companion'),false);win(s);G.resolveCombat(s,true);assert.equal(s.stage,4);assert.equal(s.morality,10);assert.ok(s.inventory.includes('Shipping manifest'));assert.equal(G.resolveCombat(s,true),false);});
test('Death wipes resources and requires respawn before recovery',()=>{const s=start();s.stage=3;s.location='docks';s.room='interior';s.hp=1;s.cash=4;G.talk(s,'vinnie');choose(s,'fight');G.combatAct(s,'guard');assert.equal(s.combat,null);assert.ok(s.death);assert.equal(s.stage,3);assert.equal(s.cash,0);assert.equal(s.hp,0);assert.equal(G.talk(s,'father'),false);assert.ok(G.respawn(s));assert.equal(s.location,'church');G.talk(s,'father');choose(s,'rest');assert.equal(s.hp,100);assert.equal(s.focus,3);});
test('Retreat preserves objective and allows re-entry',()=>{const s=start();s.stage=3;visit(s,'docks','vinnie');choose(s,'fight');G.combatAct(s,'retreat');assert.equal(s.location,'church');assert.equal(s.stage,3);visit(s,'docks','vinnie');choose(s,'fight');assert.equal(s.combat.enemy,66);});
test('Every ending threshold and final-decision modifier is exact',()=>{for(const [score,action,expected] of [[24,'loyal','purgatory'],[25,'loyal','redemption'],[-24,'loyal','purgatory'],[-25,'loyal','empire'],[5,'protect','redemption'],[-5,'rule','empire'],[-80,'protect','empire'],[80,'rule','redemption']]){const s=start();s.stage=7;s.dialog='final';s.morality=score;choose(s,action);assert.equal(s.ending,expected);}});
test('Companion abilities differ and are persisted mid-confrontation',()=>{for(const id of ['silvio','paulie','chris']){const s=start();s.stage=3;s.companion=id;visit(s,'docks','vinnie');choose(s,'fight');s.focus=0;G.combatAct(s,'companion');assert.equal(s.combat.enemy,66-(id==='silvio'?14:id==='paulie'?22:28));assert.equal(s.focus,id==='silvio'?2:0);assert.ok(G.validSave(JSON.parse(JSON.stringify(s))));}});
test('Save validation rejects malformed and incompatible saves',()=>{assert.ok(G.validSave(start()));for(const x of [null,{},[],{...start(),role:'wizard'},{...start(),cash:NaN},{...start(),stage:99},{...start(),inventory:[{}]},{...start(),companion:'nobody'},{...start(),morality:101},{...start(),version:2}])assert.equal(G.validSave(x),false);});

const I=require('../interiors.js');
test('All six buildings have reachable public and private rooms and return exits',()=>{for(const loc of Object.keys(G.locations)){const s=start();s.stage=7;assert.ok(G.travel(s,loc));assert.equal(s.room,'exterior');assert.equal(G.moveRoom(s,'backroom'),false);assert.ok(G.moveRoom(s,'interior'));assert.ok(G.roomInfo(s).desc);assert.ok(G.moveRoom(s,'backroom'));assert.ok(G.roomInfo(s).desc);assert.ok(G.moveRoom(s,'interior'));assert.ok(G.moveRoom(s,'exterior'));assert.equal(G.moveRoom(s,'unknown'),false);}});
test('Room transitions cannot bypass active dialogue, combat, locks, or endings',()=>{const s=start();G.talk(s,'tony');assert.equal(G.moveRoom(s,'interior'),false);G.act(s,'leave');s.combat={kind:'docks'};assert.equal(G.moveRoom(s,'interior'),false);s.combat=null;s.ending='redemption';assert.equal(G.moveRoom(s,'interior'),false);s.ending=null;s.started=false;assert.equal(G.moveRoom(s,'interior'),false);});
test('Characters are only interactable in the room they occupy',()=>{const s=start();assert.ok(G.nearbyPeople(s).includes('tony'));assert.ok(!G.nearbyPeople(s).includes('paulie'));assert.equal(G.talk(s,'paulie'),false);G.moveRoom(s,'interior');assert.ok(G.nearbyPeople(s).includes('paulie'));assert.ok(!G.nearbyPeople(s).includes('tony'));assert.equal(G.talk(s,'tony'),false);G.moveRoom(s,'backroom');assert.deepEqual(G.nearbyPeople(s),[]);s.stage=2;assert.ok(G.nearbyPeople(s).includes('tony'));assert.ok(!G.nearbyPeople(s).includes('paulie'));assert.ok(G.talk(s,'tony'));});
test('Legacy saves retain progress and resume conversations in the right room',()=>{const old=start();delete old.room;old.stage=4;old.location='bing';old.dialog='silvio';old.morality=35;const migrated=G.migrateSave(old);assert.equal(migrated.room,'backroom');assert.equal(migrated.stage,4);assert.equal(migrated.morality,35);assert.equal(old.room,undefined);assert.ok(G.dialogue(migrated));old.dialog=null;assert.equal(G.migrateSave(old).room,'exterior');old.combat={kind:'docks',enemy:40,round:2,log:[]};old.location='docks';assert.equal(G.migrateSave(old).room,'interior');assert.equal(G.migrateSave({...old,room:'basement'}),null);});
test('New saves persist rooms and travel always arrives outside',()=>{const s=start();G.moveRoom(s,'interior');G.moveRoom(s,'backroom');const loaded=G.migrateSave(JSON.parse(JSON.stringify(s)));assert.equal(loaded.room,'backroom');assert.ok(G.travel(loaded,'vesuvio'));assert.equal(loaded.room,'exterior');});
test('Every interior has walkable spawn, doors, NPC access, and collision-safe routes',()=>{for(const [loc,rs]of Object.entries(I.layouts))for(const [room,data]of Object.entries(rs)){const spawn={x:9.5,y:13};assert.ok(I.walkable(data,spawn.x,spawn.y),loc+room+' spawn');const targets=[{x:4.5,y:13},...(room==='interior'?[{x:16,y:3}]:[]),...Object.values(data.npc).map(([x,y])=>({x,y}))];for(const target of targets){const route=I.route(data,spawn,target);assert.ok(route.length,loc+room+' reachable '+JSON.stringify(target));for(const step of route)assert.ok(I.walkable(data,step.x,step.y),loc+room+' collision');for(let i=1;i<route.length;i++)assert.equal(Math.abs(route[i].x-route[i-1].x)+Math.abs(route[i].y-route[i-1].y),.5);}}});
test('Clicking on a table routes to nearby floor rather than walking through it',()=>{const data=I.layout('satriales','backroom');assert.equal(I.walkable(data,9,7),false);const path=I.route(data,{x:9.5,y:13},{x:9,y:7});assert.ok(path.length);assert.ok(path.every(p=>I.walkable(data,p.x,p.y)));});

test('All 24 ambient conversations leave campaign state unchanged, including repeat visits',()=>{assert.equal(Object.keys(G.ambient).length,24);const campaign=s=>JSON.stringify(Object.fromEntries(Object.entries(s).filter(([k])=>!['dialog','turn','met','ambientTopic'].includes(k))));for(const [id,npc]of Object.entries(G.ambient)){const s=start();s.stage=7;s.location=npc.location;s.room=npc.room;const before=campaign(s);for(let repeat=0;repeat<2;repeat++){assert.ok(G.talk(s,id));assert.equal(G.dialogue(s).who,id);for(let i=0;i<npc.topics.length;i++){assert.ok(G.act(s,'topic_'+i));assert.equal(G.dialogue(s).text,npc.topics[i][1]);assert.ok(G.validSave(s));}assert.ok(G.act(s,'leave'));assert.equal(campaign(s),before);}assert.equal(s.met.filter(x=>x===id).length,1);}});
test('Descriptions reveal names only after introductions and survive saves',()=>{const s=start();assert.equal(G.personLabel(s,'lou'),'Man with a delivery cap');assert.ok(G.talk(s,'lou'));assert.equal(G.personLabel(s,'lou'),'Lou Rizzo');const loaded=G.migrateSave(JSON.parse(JSON.stringify(s)));assert.equal(G.personLabel(loaded,'lou'),'Lou Rizzo');assert.equal(G.dialogue(loaded).who,'lou');const legacy=start();delete legacy.met;delete legacy.ambientTopic;assert.deepEqual(G.migrateSave(legacy).met,[]);});
test('Every background NPC has a clear approach point within speaking distance',()=>{for(const [id,npc]of Object.entries(G.ambient)){const [x,y]=npc.position;if(npc.room==='exterior'){assert.ok(x>=3&&x<=18&&y>=9.7&&y<=12.6,id);continue;}const data=I.layout(npc.location,npc.room);assert.ok(I.walkable(data,x,y),id+' not inside furniture');const path=I.route(data,{x:9.5,y:13},{x,y:y+1});assert.ok(path.length,id+' reachable');const end=path.at(-1);assert.ok(Math.hypot(end.x-x,end.y-y)<=1.6,id+' speaking distance');}});

test('Tony acknowledges the manifest from every acquisition route and directs the player to Silvio',()=>{
 for(const method of ['reason','bribe','fight']){const s=start();s.stage=3;visit(s,'docks','vinnie');choose(s,method);if(method==='fight'){win(s);G.resolveCombat(s,true);}assert.equal(s.stage,4);assert.ok(s.inventory.includes('Shipping manifest'));const resources={cash:s.cash,xp:s.xp,respect:s.respect,morality:s.morality};visit(s,'satriales','tony');assert.match(G.dialogue(s).text,/You got the manifest/);assert.match(G.dialogue(s).text,/Silvio at the Bada Bing/);choose(s,'silvio');assert.equal(s.stage,4);for(const k of Object.keys(resources))assert.equal(s[k],resources[k]);G.talk(s,'tony');choose(s,'silvio');visit(s,'bing','silvio');choose(s,'investigate');assert.equal(s.stage,5);visit(s,'satriales','tony');assert.match(G.dialogue(s).text,/Silvio went through the manifest/);assert.match(G.dialogue(s).text,/Anna Conti/);}
});
test('Existing mid-dialogue saves and lost inventory retain Tony’s correct manifest acknowledgement',()=>{
 const s=start();s.stage=4;s.location='satriales';s.room='backroom';s.dialog='tony';s.inventory=['Shipping manifest'];let loaded=G.migrateSave(JSON.parse(JSON.stringify(s)));assert.match(G.dialogue(loaded).text,/You got the manifest/);loaded.inventory=[];assert.match(G.dialogue(loaded).text,/You recovered the manifest/);choose(loaded,'silvio');visit(loaded,'bing','silvio');choose(loaded,'investigate');assert.equal(loaded.stage,5);
});
